// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}

public enum ErrorResponse : ErrorType {
    case Error(Int, NSData?, ErrorType)
}

public class Response<T> {
    public let statusCode: Int
    public let header: [String: String]
    public let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: NSHTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = dispatch_once_t()
class Decoders {
    static private var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()

    static func addDecoder<T>(clazz clazz: T.Type, decoder: ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as! AnyObject }
    }

    static func decode<T>(clazz clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }

    static func decode<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictionary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictionary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }

    static func decode<T>(clazz clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if T.self is Int32.Type && source is NSNumber {
            return source.intValue as! T;
        }
        if T.self is Int64.Type && source is NSNumber {
            return source.longLongValue as! T;
        }
        if T.self is NSUUID.Type && source is String {
            return NSUUID(UUIDString: source as! String) as! T
        }
        if source is T {
            return source as! T
        }
        if T.self is NSData.Type && source is String {
            return NSData(base64EncodedString: source as! String, options: NSDataBase64DecodingOptions()) as! T
        }

        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static private func initialize() {
        dispatch_once(&once) {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'",
                "yyyy-MM-dd'T'HH:mm:ss.SSS"
            ].map { (format: String) -> NSDateFormatter in
                let formatter = NSDateFormatter()
                formatter.dateFormat = format
                return formatter
            }
            // Decoder for NSDate
            Decoders.addDecoder(clazz: NSDate.self) { (source: AnyObject) -> NSDate in
               if let sourceString = source as? String {
                    for formatter in formatters {
                        if let date = formatter.dateFromString(sourceString) {
                            return date
                        }
                    }

                }
                if let sourceInt = source as? Int {
                    // treat as a java date
                    return NSDate(timeIntervalSince1970: Double(sourceInt / 1000) )
                }
                fatalError("formatter failed to parse \(source)")
            } 

            // Decoder TTTTTTTTTTESTTTTTT for [CardDetail]
            Decoders.addDecoder(clazz: [CardDetail].self) { (source: AnyObject) -> [CardDetail] in
                return Decoders.decode(clazz: [CardDetail].self, source: source)
            }
            // Decoder for CardDetail
            Decoders.addDecoder(clazz: CardDetail.self) { (source: AnyObject) -> CardDetail in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = CardDetail()
                instance.type = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"])
                instance.title = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["title"])
                instance.subtitle = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["subtitle"])
                instance.image = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["image"])
                instance.anchorX = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["anchor_x"])
                instance.anchorY = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["anchor_y"])
                instance.shareUrl = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["share_url"])
                instance.containers = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["containers"])
                return instance
            }


            // Decoder TTTTTTTTTTESTTTTTT for [CardDetailContainers]
            Decoders.addDecoder(clazz: [CardDetailContainers].self) { (source: AnyObject) -> [CardDetailContainers] in
                return Decoders.decode(clazz: [CardDetailContainers].self, source: source)
            }
            // Decoder for CardDetailContainers
            Decoders.addDecoder(clazz: CardDetailContainers.self) { (source: AnyObject) -> CardDetailContainers in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = CardDetailContainers()
                instance.type = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"])
                return instance
            }


            // Decoder TTTTTTTTTTESTTTTTT for [CardRelations]
            Decoders.addDecoder(clazz: [CardRelations].self) { (source: AnyObject) -> [CardRelations] in
                return Decoders.decode(clazz: [CardRelations].self, source: source)
            }
            // Decoder for CardRelations
            Decoders.addDecoder(clazz: CardRelations.self) { (source: AnyObject) -> CardRelations in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = CardRelations()
                instance.relType = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["rel_type"])
                instance.cards = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["cards"])
                return instance
            }


            // Decoder TTTTTTTTTTESTTTTTT for [ChannelReady]
            Decoders.addDecoder(clazz: [ChannelReady].self) { (source: AnyObject) -> [ChannelReady] in
                return Decoders.decode(clazz: [ChannelReady].self, source: source)
            }
            // Decoder for ChannelReady
            Decoders.addDecoder(clazz: ChannelReady.self) { (source: AnyObject) -> ChannelReady in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = ChannelReady()
                instance.channelId = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["channel_id"])
                instance.ready = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["ready"])
                return instance
            }


            // Decoder TTTTTTTTTTESTTTTTT for [DynamicServer]
            Decoders.addDecoder(clazz: [DynamicServer].self) { (source: AnyObject) -> [DynamicServer] in
                return Decoders.decode(clazz: [DynamicServer].self, source: source)
            }
            // Decoder for DynamicServer
            Decoders.addDecoder(clazz: DynamicServer.self) { (source: AnyObject) -> DynamicServer in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = DynamicServer()
                instance.hostname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["hostname"])
                instance.port = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["port"])
                instance.channel = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["channel"])
                return instance
            }


            // Decoder TTTTTTTTTTESTTTTTT for [MovieReady]
            Decoders.addDecoder(clazz: [MovieReady].self) { (source: AnyObject) -> [MovieReady] in
                return Decoders.decode(clazz: [MovieReady].self, source: source)
            }
            // Decoder for MovieReady
            Decoders.addDecoder(clazz: MovieReady.self) { (source: AnyObject) -> MovieReady in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = MovieReady()
                instance.movieId = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["movie_id"])
                instance.ready = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["ready"])
                return instance
            }


            // Decoder TTTTTTTTTTESTTTTTT for [StaticCard]
            Decoders.addDecoder(clazz: [StaticCard].self) { (source: AnyObject) -> [StaticCard] in
                return Decoders.decode(clazz: [StaticCard].self, source: source)
            }
            // Decoder for StaticCard
            Decoders.addDecoder(clazz: StaticCard.self) { (source: AnyObject) -> StaticCard in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = StaticCard()
                instance.cardId = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["card_id"])
                instance.type = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"])
                instance.title = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["title"])
                instance.subtitle = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["subtitle"])
                instance.image = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["image"])
                instance.anchorX = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["anchor_x"])
                instance.anchorY = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["anchor_y"])
                instance.relations = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["relations"])
                return instance
            }
        }
    }
}
