//
// CardRelations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CardRelations: JSONEncodable {
    /** Type of the relation between the parent and the related card. */
    public var relType: String?
    /** Related cards (childrens) */
    public var cards: [StaticCard]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["rel_type"] = self.relType
        nillableDictionary["cards"] = self.cards?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
