//
// ChannelReady.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ChannelReady: JSONEncodable {
    /** The channel ID provided in the request. */
    public var channelId: String?
    /** True if the movie is ready, False otherwise. */
    public var ready: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["channel_id"] = self.channelId
        nillableDictionary["ready"] = self.ready
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
