//
// DynamicServer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DynamicServer: JSONEncodable {
    /** The hostname of the dynamic information server. */
    public var hostname: String?
    /** The port of the dynamic information server. */
    public var port: Double?
    /** The channel on the dynamic information server to be used. */
    public var channel: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["hostname"] = self.hostname
        nillableDictionary["port"] = self.port
        nillableDictionary["channel"] = self.channel
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
