//
// MovieReady.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MovieReady: JSONEncodable {
    /** The movie ID provided in the request. */
    public var movieId: String?
    /** True if the movie is ready, False otherwise. */
    public var ready: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["movie_id"] = self.movieId
        nillableDictionary["ready"] = self.ready
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
