//
// StaticCard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class StaticCard: JSONEncodable {
    /** The ID of the card. */
    public var cardId: String?
    /** The type of the card. */
    public var type: String?
    /** Title of the card. */
    public var title: String?
    /** Subtitle of the card. */
    public var subtitle: String?
    /** Image of the card. */
    public var image: String?
    /** Anchor in X axis. Value in range [0, 100]. */
    public var anchorX: Double?
    /** Anchor in Y axis. Value in range [0, 100]. */
    public var anchorY: Double?
    public var relations: [CardRelations]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["card_id"] = self.cardId
        nillableDictionary["type"] = self.type
        nillableDictionary["title"] = self.title
        nillableDictionary["subtitle"] = self.subtitle
        nillableDictionary["image"] = self.image
        nillableDictionary["anchor_x"] = self.anchorX
        nillableDictionary["anchor_y"] = self.anchorY
        nillableDictionary["relations"] = self.relations?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
